In [1]:
"""The main class that supplies other files"""
import kagglehub
import pickle
import os
import joblib
import pandas as pd
import numpy as np
import spacy
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics import f1_score
from sklearn.preprocessing import FunctionTransformer

In [3]:
import kagglehub
cwd=os.getcwd()
os.chdir(cwd)
# Download latest version
path = kagglehub.dataset_download("jackksoncsie/spam-email-dataset")
print(f'path to download, {path}')

Warning: Looks like you're using an outdated `kagglehub` version (installed: 1.0.1), please consider upgrading to the latest version (1.0.2)path to download, /Users/imohekpenyong/.cache/kagglehub/datasets/jackksoncsie/spam-email-dataset/versions/1

In [4]:
!pip install -U spacy --quiet
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 23.1 MB/s  0:00:00.9 MB/s eta 0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [4]:
df= pd.read_csv(f'{path}/emails.csv')

In [5]:
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [8]:
df.spam=df.spam.map({0:'Spam', 1:'Not Spam'})
print(df.head())
df.text.str.len().sum()

                                                text      spam
0  Subject: naturally irresistible your corporate...  Not Spam
1  Subject: the stock trading gunslinger  fanny i...  Not Spam
2  Subject: unbelievable new homes made easy  im ...  Not Spam
3  Subject: 4 color printing special  request add...  Not Spam
4  Subject: do not have money , get software cds ...  Not Spam

np.int64(8917171)

In [22]:
nlp=spacy.load('en_core_web_sm') # Function to clean and process the data for training
def extract(df):
    #df=pd.DataFrame(x,columns=['text'])
    def lemma(text): 
        doc=nlp(''.join(text)) 
        tok=[token.lemma_ for token in doc 
             if not token.is_punct and not token.is_stop] 
        return ' '.join(tok) 
    df['text']=df['text'].str.lower().apply(lemma)
    return df

In [34]:
df_one= extract(df.copy())

In [36]:
print(df_one['text'].str.len().sum())
print(df.spam.value_counts(normalize=True))  #Checking to see how unbalanced is the dataset
df.head()

5807365
spam
0    0.761173
1    0.238827
Name: proportion, dtype: float64

                                                text  spam
0  subject naturally irresistible corporate ident...     1
1  subject stock trading gunslinger   fanny merri...     1
2  subject unbelievable new home easy   m want   ...     1
3  subject 4 color print special   request additi...     1
4  subject money software cd   software compatibi...     1

In [37]:
Xtrain, Xtest, ytrain, ytest=train_test_split(df_one['text'].values,df_one['spam'].values,
                                              test_size=.1,
                                              random_state=42,
                                              shuffle=True)

#text_proc = FunctionTransformer(extract)
pipe=Pipeline([('transformer',TfidfVectorizer()),
               ('model', LinearSVC())
              ]
             )
params = [
    {
        'model': [LinearSVC()],
        'model__C': np.linspace(0.5, 2, 6),
        'model__class_weight': [{0: 1, 1: v} for v in range(1, 6)]
    },
    {
        'model': [LogisticRegression(max_iter=1000)],
        'model__C': np.linspace(0.5, 2, 6),
        'model__class_weight': [{0: 1, 1: v} for v in range(1, 6)]
    }
    ]
grid= GridSearchCV(pipe,
                 param_grid=params,
                 cv=5,
                 scoring=make_scorer(f1_score),
                 refit=True,
                verbose=10
                 )

In [38]:
print(Xtrain.shape, Xtest.shape, ytrain.shape, ytest.shape)

(5155,) (573,) (5155,) (573,)

In [88]:
model_1= grid.fit(Xtrain, ytrain)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
[CV 1/5; 1/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1}
[CV 1/5; 1/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1};, score=0.992 total time=   0.3s
[CV 2/5; 1/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1}
[CV 2/5; 1/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1};, score=0.989 total time=   0.2s
[CV 3/5; 1/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1}
[CV 3/5; 1/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1};, score=0.997 total time=   0.2s
[CV 4/5; 1/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1}
[CV 4/5; 1/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1};, score=0.992 total time=   0.2s
[CV 5/5; 1/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1}
[CV 5/5; 1/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 1};, score=0.992 total time=   0.2s
[CV 1/5; 2/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2}
[CV 1/5; 2/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2};, score=0.992 total time=   0.2s
[CV 2/5; 2/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2}
[CV 2/5; 2/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2};, score=0.989 total time=   0.2s
[CV 3/5; 2/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2}
[CV 3/5; 2/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2};, score=0.996 total time=   0.3s
[CV 4/5; 2/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2}
[CV 4/5; 2/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2};, score=0.995 total time=   0.2s
[CV 5/5; 2/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2}
[CV 5/5; 2/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 2};, score=0.992 total time=   0.2s
[CV 1/5; 3/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3}
[CV 1/5; 3/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3};, score=0.993 total time=   0.3s
[CV 2/5; 3/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3}
[CV 2/5; 3/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3};, score=0.988 total time=   0.3s
[CV 3/5; 3/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3}
[CV 3/5; 3/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3};, score=0.997 total time=   0.2s
[CV 4/5; 3/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3}
[CV 4/5; 3/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3};, score=0.995 total time=   0.2s
[CV 5/5; 3/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3}
[CV 5/5; 3/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 3};, score=0.991 total time=   0.3s
[CV 1/5; 4/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4}
[CV 1/5; 4/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4};, score=0.993 total time=   0.2s
[CV 2/5; 4/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4}
[CV 2/5; 4/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4};, score=0.990 total time=   0.2s
[CV 3/5; 4/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4}
[CV 3/5; 4/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4};, score=0.997 total time=   0.3s
[CV 4/5; 4/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4}
[CV 4/5; 4/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4};, score=0.994 total time=   0.3s
[CV 5/5; 4/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4}
[CV 5/5; 4/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 4};, score=0.990 total time=   0.3s
[CV 1/5; 5/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5}
[CV 1/5; 5/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5};, score=0.994 total time=   0.3s
[CV 2/5; 5/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5}
[CV 2/5; 5/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5};, score=0.990 total time=   0.3s
[CV 3/5; 5/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5}
[CV 3/5; 5/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5};, score=0.997 total time=   0.3s
[CV 4/5; 5/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5}
[CV 4/5; 5/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5};, score=0.994 total time=   0.3s
[CV 5/5; 5/60] START model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5}
[CV 5/5; 5/60] END model=LinearSVC(), model__C=0.5, model__class_weight={0: 1, 1: 5};, score=0.990 total time=   0.3s
[CV 1/5; 6/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1}
[CV 1/5; 6/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1};, score=0.992 total time=   0.2s
[CV 2/5; 6/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1}
[CV 2/5; 6/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1};, score=0.989 total time=   0.2s
[CV 3/5; 6/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1}
[CV 3/5; 6/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1};, score=0.996 total time=   0.3s
[CV 4/5; 6/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1}
[CV 4/5; 6/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1};, score=0.993 total time=   0.3s
[CV 5/5; 6/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1}
[CV 5/5; 6/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 1};, score=0.992 total time=   0.3s
[CV 1/5; 7/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2}
[CV 1/5; 7/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2};, score=0.992 total time=   0.3s
[CV 2/5; 7/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2}
[CV 2/5; 7/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2};, score=0.988 total time=   0.3s
[CV 3/5; 7/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2}
[CV 3/5; 7/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2};, score=0.996 total time=   0.2s
[CV 4/5; 7/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2}
[CV 4/5; 7/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2};, score=0.995 total time=   0.2s
[CV 5/5; 7/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2}
[CV 5/5; 7/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 2};, score=0.992 total time=   0.2s
[CV 1/5; 8/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3}
[CV 1/5; 8/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3};, score=0.992 total time=   0.3s
[CV 2/5; 8/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3}
[CV 2/5; 8/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3};, score=0.988 total time=   0.2s
[CV 3/5; 8/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3}
[CV 3/5; 8/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3};, score=0.997 total time=   0.3s
[CV 4/5; 8/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3}
[CV 4/5; 8/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3};, score=0.995 total time=   0.3s
[CV 5/5; 8/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3}
[CV 5/5; 8/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 3};, score=0.992 total time=   0.2s
[CV 1/5; 9/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4}
[CV 1/5; 9/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4};, score=0.992 total time=   0.2s
[CV 2/5; 9/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4}
[CV 2/5; 9/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4};, score=0.990 total time=   0.3s
[CV 3/5; 9/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4}
[CV 3/5; 9/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4};, score=0.997 total time=   0.3s
[CV 4/5; 9/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4}
[CV 4/5; 9/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4};, score=0.995 total time=   0.3s
[CV 5/5; 9/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4}
[CV 5/5; 9/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 4};, score=0.992 total time=   0.3s
[CV 1/5; 10/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5}
[CV 1/5; 10/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5};, score=0.992 total time=   0.2s
[CV 2/5; 10/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5}
[CV 2/5; 10/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5};, score=0.991 total time=   0.3s
[CV 3/5; 10/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5}
[CV 3/5; 10/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5};, score=0.997 total time=   0.3s
[CV 4/5; 10/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5}
[CV 4/5; 10/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5};, score=0.994 total time=   0.3s
[CV 5/5; 10/60] START model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5}
[CV 5/5; 10/60] END model=LinearSVC(), model__C=0.8, model__class_weight={0: 1, 1: 5};, score=0.992 total time=   0.3s
[CV 1/5; 11/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1}
[CV 1/5; 11/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1};, score=0.991 total time=   0.2s
[CV 2/5; 11/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1}
[CV 2/5; 11/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1};, score=0.989 total time=   0.2s
[CV 3/5; 11/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1}
[CV 3/5; 11/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1};, score=0.996 total time=   0.2s
[CV 4/5; 11/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1}
[CV 4/5; 11/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1};, score=0.994 total time=   0.2s
[CV 5/5; 11/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1}
[CV 5/5; 11/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 1};, score=0.993 total time=   0.2s
[CV 1/5; 12/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2}
[CV 1/5; 12/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2};, score=0.991 total time=   0.2s
[CV 2/5; 12/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2}
[CV 2/5; 12/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2};, score=0.988 total time=   0.2s
[CV 3/5; 12/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2}
[CV 3/5; 12/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2};, score=0.996 total time=   0.3s
[CV 4/5; 12/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2}
[CV 4/5; 12/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2};, score=0.995 total time=   0.3s
[CV 5/5; 12/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2}
[CV 5/5; 12/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 2};, score=0.993 total time=   0.2s
[CV 1/5; 13/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3}
[CV 1/5; 13/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3};, score=0.992 total time=   0.2s
[CV 2/5; 13/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3}
[CV 2/5; 13/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3};, score=0.988 total time=   0.2s
[CV 3/5; 13/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3}
[CV 3/5; 13/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3};, score=0.997 total time=   0.3s
[CV 4/5; 13/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3}
[CV 4/5; 13/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3};, score=0.995 total time=   0.3s
[CV 5/5; 13/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3}
[CV 5/5; 13/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 3};, score=0.993 total time=   0.2s
[CV 1/5; 14/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4}
[CV 1/5; 14/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4};, score=0.992 total time=   0.3s
[CV 2/5; 14/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4}
[CV 2/5; 14/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4};, score=0.988 total time=   0.3s
[CV 3/5; 14/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4}
[CV 3/5; 14/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4};, score=0.997 total time=   0.3s
[CV 4/5; 14/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4}
[CV 4/5; 14/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4};, score=0.995 total time=   0.3s
[CV 5/5; 14/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4}
[CV 5/5; 14/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 4};, score=0.992 total time=   0.3s
[CV 1/5; 15/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5}
[CV 1/5; 15/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5};, score=0.992 total time=   0.3s
[CV 2/5; 15/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5}
[CV 2/5; 15/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5};, score=0.989 total time=   0.3s
[CV 3/5; 15/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5}
[CV 3/5; 15/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5};, score=0.997 total time=   0.3s
[CV 4/5; 15/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5}
[CV 4/5; 15/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5};, score=0.994 total time=   0.3s
[CV 5/5; 15/60] START model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5}
[CV 5/5; 15/60] END model=LinearSVC(), model__C=1.1, model__class_weight={0: 1, 1: 5};, score=0.992 total time=   0.3s
[CV 1/5; 16/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1}
[CV 1/5; 16/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1};, score=0.991 total time=   0.3s
[CV 2/5; 16/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1}
[CV 2/5; 16/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1};, score=0.989 total time=   0.3s
[CV 3/5; 16/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1}
[CV 3/5; 16/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1};, score=0.996 total time=   0.2s
[CV 4/5; 16/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1}
[CV 4/5; 16/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1};, score=0.994 total time=   0.2s
[CV 5/5; 16/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1}
[CV 5/5; 16/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 1};, score=0.993 total time=   0.2s
[CV 1/5; 17/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2}
[CV 1/5; 17/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2};, score=0.990 total time=   0.3s
[CV 2/5; 17/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2}
[CV 2/5; 17/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2};, score=0.988 total time=   0.3s
[CV 3/5; 17/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2}
[CV 3/5; 17/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2};, score=0.996 total time=   0.3s
[CV 4/5; 17/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2}
[CV 4/5; 17/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2};, score=0.995 total time=   0.2s
[CV 5/5; 17/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2}
[CV 5/5; 17/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 2};, score=0.993 total time=   0.3s
[CV 1/5; 18/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3}
[CV 1/5; 18/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3};, score=0.991 total time=   0.3s
[CV 2/5; 18/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3}
[CV 2/5; 18/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3};, score=0.988 total time=   0.3s
[CV 3/5; 18/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3}
[CV 3/5; 18/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3};, score=0.996 total time=   0.3s
[CV 4/5; 18/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3}
[CV 4/5; 18/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3};, score=0.995 total time=   0.3s
[CV 5/5; 18/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3}
[CV 5/5; 18/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 3};, score=0.993 total time=   0.3s
[CV 1/5; 19/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4}
[CV 1/5; 19/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4};, score=0.991 total time=   0.3s
[CV 2/5; 19/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4}
[CV 2/5; 19/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4};, score=0.988 total time=   0.3s
[CV 3/5; 19/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4}
[CV 3/5; 19/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4};, score=0.997 total time=   0.3s
[CV 4/5; 19/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4}
[CV 4/5; 19/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4};, score=0.995 total time=   0.3s
[CV 5/5; 19/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4}
[CV 5/5; 19/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 4};, score=0.993 total time=   0.3s
[CV 1/5; 20/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 5}
[CV 1/5; 20/60] END model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 5};, score=0.992 total time=   0.3s
[CV 2/5; 20/60] START model=LinearSVC(), model__C=1.4, model__class_weight={0: 1, 1: 5}

In [90]:
model_1.best_estimator_

Pipeline(steps=[('transformer', TfidfVectorizer()),
                ('model',
                 LinearSVC(C=np.float64(0.8), class_weight={0: 1, 1: 4}))])

In [92]:
f1_score(model_1.best_estimator_.predict(Xtest), ytest)

0.9898305084745763

In [ ]:
t= [r"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the"]
doc= nlp(''.join(t))
for token in doc:
    print(token.lemma_)

In [94]:
mod.best_estimator_.predict([r"""Hello Micah,We have received your application for the Data Analytics Specialist position. 
Thank you for your interest. We'll be in touch once we've been able to review your application.
In the meantime, why not learn more about us
At BT we believe in empowering our people to thrive and make a real impact."""])

array([1])

### Model depolyment

In [51]:
with open('trained_model', 'wb') as model:
    pickle.dump(model_1, model)


def prediction(text):
    with open('trained_model', 'rb') as model:
        model=pickle.load(model)
        print('Spam') if model.best_estimator_.predict(text)==1 else print('Not Spam')

In [62]:
prediction([r"""Hello Micah,We have received your application for the Data Analytics Specialist position. 
Thank you for your interest. We'll be in touch once we've been able to review your application.
In the meantime, why not learn more about us
At BT we believe in empowering our people to thrive and make a real impact."""])

Spam

In [14]:
Xtrain2, Xtest2, ytrain2, ytest2=train_test_split(df['text'].values,df['spam'].values,
                                              test_size=.1,
                                              random_state=42,
                                              shuffle=True)

#text_proc = FunctionTransformer(extract)
pipe=Pipeline([('transformer',TfidfVectorizer()),
               ('model', LinearSVC())
              ]
             )
params = [
    {
        'model': [LinearSVC()],
        'model__C': np.linspace(0.5, 2, 6),
        'model__class_weight': [{'Spam': 1, 'Not Spam': v} for v in range(1, 6)]
    },
    {
        'model': [LogisticRegression(max_iter=1000)],
        'model__C': np.linspace(0.5, 2, 6),
        'model__class_weight': [{'Spam': 1, 'Not Spam': v} for v in range(1, 6)]
    }
    ]

In [21]:
import joblib
import os

pipe2 = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        ngram_range=(1, 2),
        min_df=2,
        max_features=30000,
        sublinear_tf=True
    )),
    ("model", LinearSVC())
])

model_2= GridSearchCV(pipe2,
                 param_grid=params,
                 cv=5,
                scoring=f1_score,
                refit=True
                 )

In [22]:
model_2.fit(Xtrain2, ytrain2)

/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3160, in _bind
    raise TypeError(
        'too many positional arguments') from None
TypeError: too many positional arguments

  warnings.warn(
/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/Users/imohekpenyong/anaconda3/envs/end2end/lib/python3.14/inspect.py", line 3236, in bind
    return self._bind(args, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('tfidf',
                                        TfidfVectorizer(max_features=30000,
                                                        min_df=2,
                                                        ngram_range=(1, 2),
                                                        sublinear_tf=True)),
                                       ('model', LinearSVC())]),
             param_grid=[{'model': [LinearSVC()],
                          'model__C': array([0.5, 0.8, 1.1, 1.4, 1.7, 2. ]),
                          'model__class_weight': [{'Not Spam': 1, 'Spam': 1},
                                                  {'Not Spam': 2, 'Spam': 1},
                                                  {'Not Spam': 3, 'Spam': 1},
                                                  {'Not Spam': 4, 'Spam': 1},
                                                  {'Not Spam': 5, 'Spam': 1}]},
                         {'model': [LogisticRegression(max_iter=1000)],
                          'model__C': array([0.5, 0.8, 1.1, 1.4, 1.7, 2. ]),
                          'model__class_weight': [{'Not Spam': 1, 'Spam': 1},
                                                  {'Not Spam': 2, 'Spam': 1},
                                                  {'Not Spam': 3, 'Spam': 1},
                                                  {'Not Spam': 4, 'Spam': 1},
                                                  {'Not Spam': 5, 'Spam': 1}]}],
             scoring=<function f1_score at 0x16591a1f0>)

In [23]:
model_2.best_estimator_

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=30000, min_df=2,
                                 ngram_range=(1, 2), sublinear_tf=True)),
                ('model',
                 LinearSVC(C=np.float64(0.5),
                           class_weight={'Not Spam': 1, 'Spam': 1}))])

In [33]:
model_2.score

<bound method BaseSearchCV.score of GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('tfidf',
                                        TfidfVectorizer(max_features=30000,
                                                        min_df=2,
                                                        ngram_range=(1, 2),
                                                        sublinear_tf=True)),
                                       ('model', LinearSVC())]),
             param_grid=[{'model': [LinearSVC()],
                          'model__C': array([0.5, 0.8, 1.1, 1.4, 1.7, 2. ]),
                          'model__class_weight': [{'Not Spam': 1, 'Spam': 1},
                                                  {'Not Spam': 2, 'Spam': 1},
                                                  {'Not Spam': 3, 'Spam': 1},
                                                  {'Not Spam': 4, 'Spam': 1},
                                                  {'Not Spam': 5, 'Spam': 1}]},
                         {'model': [LogisticRegression(max_iter=1000)],
                          'model__C': array([0.5, 0.8, 1.1, 1.4, 1.7, 2. ]),
                          'model__class_weight': [{'Not Spam': 1, 'Spam': 1},
                                                  {'Not Spam': 2, 'Spam': 1},
                                                  {'Not Spam': 3, 'Spam': 1},
                                                  {'Not Spam': 4, 'Spam': 1},
                                                  {'Not Spam': 5, 'Spam': 1}]}],
             scoring=<function f1_score at 0x16591a1f0>)>

In [31]:
model_2.best_estimator_.score( Xtest2, ytest2)

0.9947643979057592

In [39]:
string=r"""Hello Micah,
We have received your application for the Data Analytics Specialist position. 
Thank you for your interest. We'll be in touch once we've been able to review your application.
In the meantime, why not learn more about us
At BT we believe in empowering our people to thrive and make a real impact."""

In [40]:
model_2.best_estimator_.predict([string])

array(['Spam'], dtype=object)

In [30]:
path = os.path.join(os.path.dirname(os.getcwd()), "models")
joblib.dump(model_2.best_estimator_, f'{path}/spam_model.joblib')

['/Users/imohekpenyong/sentiment_analysis/models/spam_model.joblib']